package Quran::Web::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Quran::Web::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:nextgen',
        user => 'root',
        password => 'crackme',
    }
);

=head1 NAME

Quran::Web::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Quran::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Quran::Web::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
